package com.cherry.framework.dao;

import com.cherry.framework.model.DeptEntity;
import java.util.List;

public interface DeptEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_dept
     *
     * @mbggenerated
     */
    int insert(DeptEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_dept
     *
     * @mbggenerated
     */
    DeptEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_dept
     *
     * @mbggenerated
     */
    List<DeptEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeptEntity record);
}