package com.cherry.framework.dao;

import com.cherry.framework.model.MenuEntity;
import java.util.List;

public interface MenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu
     *
     * @mbggenerated
     */
    int insert(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu
     *
     * @mbggenerated
     */
    MenuEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu
     *
     * @mbggenerated
     */
    List<MenuEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuEntity record);
}