package com.cherry.framework.dao;

import com.cherry.framework.model.RoleMenuEntity;
import java.util.List;

public interface RoleMenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_menu
     *
     * @mbggenerated
     */
    int insert(RoleMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_menu
     *
     * @mbggenerated
     */
    RoleMenuEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_menu
     *
     * @mbggenerated
     */
    List<RoleMenuEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleMenuEntity record);
}