package com.cherry.framework.dao;

import com.cherry.framework.model.UserDeptEntity;
import java.util.List;

public interface UserDeptEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user_dept
     *
     * @mbggenerated
     */
    int insert(UserDeptEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user_dept
     *
     * @mbggenerated
     */
    UserDeptEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user_dept
     *
     * @mbggenerated
     */
    List<UserDeptEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDeptEntity record);
}