package com.cherry.framework.platform.dao;

import com.cherry.framework.platform.model.LogEntity;
import java.util.List;

public interface LogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_log
     *
     * @mbggenerated
     */
    int insert(LogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_log
     *
     * @mbggenerated
     */
    LogEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_log
     *
     * @mbggenerated
     */
    List<LogEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogEntity record);
}