package com.cherry.framework.platform.dao;

import com.cherry.framework.platform.model.MenuPrivilegeEntity;
import java.util.List;

public interface MenuPrivilegeEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu_privilege
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu_privilege
     *
     * @mbggenerated
     */
    int insert(MenuPrivilegeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu_privilege
     *
     * @mbggenerated
     */
    MenuPrivilegeEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu_privilege
     *
     * @mbggenerated
     */
    List<MenuPrivilegeEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_menu_privilege
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MenuPrivilegeEntity record);
}