package com.cherry.framework.platform.dao;

import com.cherry.framework.platform.model.RoleResourceEntity;
import java.util.List;

public interface RoleResourceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbggenerated
     */
    int insert(RoleResourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbggenerated
     */
    RoleResourceEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbggenerated
     */
    List<RoleResourceEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_role_resource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleResourceEntity record);
}