package com.cherry.framework.platform.dao;

import com.cherry.framework.platform.model.UserEntity;
import java.util.List;

public interface UserEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbggenerated
     */
    int insert(UserEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbggenerated
     */
    UserEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbggenerated
     */
    List<UserEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fr_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserEntity record);

    /**
     *  根据用户名查询用户
     *
     * @param loginName
     * @return
     */
    UserEntity findUserByLoginName(String loginName);
}